# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_userroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroom',
            unique_together=set([('user', 'room')]),
        ),
    ]
